- name: Install Homebrew
  block:
    - name: Install Homebrew dependencies
      become: true
      apt:
        name:
          - sudo
          - bash
          - curl
          - git
    - name: Install Homebrew
      block:
        - name: Ensuring Homebrew Is Installed
          stat:
            path: $HOME/.homebrew/bin/brew
          register: homebrew_check
        - name: Install Homebrew
          shell: |
            yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | sed 's/HOMEBREW_PREFIX=".*"/HOMEBREW_PREFIX="$HOME\/.homebrew"/g')"
            (echo; echo 'eval "$($HOME/.homebrew/bin/brew shellenv)"') >> ~/.bashrc
          when:
            - not homebrew_check.stat.exists
  tags:
    - brew
