- block:
  - name: Install wget
    become: true
    apt:
      name:
        - wget 
  - name: Install miniconda
    shell: wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && bash ~/miniconda.sh -b -p {{ miniconda_prefix }} && rm -rf ~/miniconda.sh
  tags:
    - conda
- block:
  - name: Install curl and bzip2
    become: true
    apt:
      name:
        - curl
        - bzip2
  - name: Install micromamba
    shell: curl micro.mamba.pm/install.sh | sed 's/PREFIXLOCATION=".*"/PREFIXLOCATION="$HOME\/.local\/.micromamba"/g' | bash
  tags:
    - mamba
