- name: Core setup
  become: true
  block:
    - name: Install core packages
      apt:
        name:
          - sudo
          - build-essential
          - software-properties-common
          - pkg-config
          - ca-certificates
          - locales
          - bash
          - curl
          - wget
          - git
          - unzip
          - make
          - cmake
          - cron
          - tmux
          - vim
    - name: Ensure en_US.UTF8 locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present
  tags:
    - core
- name: Full setup
  become: true
  block:
    - name: Install Python
      apt:
        name:
          - python3-pip
          - python3-venv
    - name: Install Go
      apt:
        name:
          - golang-go
    - name: diff-so-fancy ppa
      apt_repository:
        repo: ppa:aos1/diff-so-fancy
        state: present
        update_cache: True
    - name: Install productivity tools
      apt:
        name:
          - zsh
          - aria2
          - rsync
          - git-lfs
          - tree
          - tldr
          - fzf
          - ack
          - silversearcher-ag
          - fd-find
          - ripgrep
          - bat
          - exa
          - diff-so-fancy
          - xclip
          - xsel
          - lm-sensors
          - htop
          - btop
          - nvtop
          - gh
- name: Install optional packages
  become: true
  apt:
    name:
      - imagemagick
      - ffmpeg
      - yt-dlp
  tags:
    - never
