- name: Install and configure dotfiles
  block:
    - name: Installing stow and git
      become: true
      apt:
        name:
          - git
          - stow
    - name: Cloning .dotfiles
      git:
        repo: 'git@github.com:desmondchchan/.dotfiles.git'
        dest: "{{ ansible_env.HOME }}/.dotfiles"
        recursive: yes
        update: yes
        accept_hostkey: yes
        version: main
    - name: Ensure presence of directories
      file:
        path: '{{ item }}'
        state: directory
      with_items:
        - "{{ ansible_env.HOME }}/.local/bin"
        - "{{ ansible_env.HOME }}/.tmux"
        - "{{ ansible_env.HOME }}/.config/lvim"
        - "{{ ansible_env.HOME }}/.config/lazygit"
    - name: Ensure absence of existing dotfiles
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - "{{ ansible_env.HOME }}/.profile"
    - name: Stow dotfiles
      shell: cd {{ ansible_env.HOME }}/.dotfiles && stow */
  tags:
    - dotfiles
