- name: Install and configure node
  environment:
    PATH: "{{ npm_prefix }}/bin:{{ ansible_env.PATH }}"
    N_PREFIX: "{{ n_prefix }}"
  tags:
    - node
  block:
    - name: Install node and npm
      become: true
      apt:
        name:
          - nodejs
          - npm
    - name: Create a directory for npm
      file:
        path: "{{ npm_prefix }}"
        state: directory
        mode: '0755'
    - name: Set npm prefix
      shell: npm config set prefix '{{ npm_prefix }}'
    - name: Install curl and wget
      become: true
      apt:
        name:
          - curl
          - wget
    - name: Install N
      npm:
        name: n
        global: yes
    - name: Create a directory for n
      file:
        path: "{{ n_prefix }}"
        state: directory
        mode: '0755'
    - name: Install correct version of Node
      shell: n 14
- name: Install npm packages
  block:
    - name: Install Yarn
      npm:
        name: yarn
        global: yes
    - name: Install eslint
      npm:
        name: eslint
        global: yes
    - name: Install Typescript language server
      npm:
        name: typescript-language-server
        global: yes
    - name: Install Typescript
      npm:
        name: typescript
        global: yes
    - name: Install TS-Node
      npm:
        name: ts-node
        global: yes
  tags:
    - node
