- name: Install and configure neovim
  become: true
  block:
    - name: neovim unstable ppa
      apt_repository:
        repo: ppa:neovim-ppa/unstable
        state: present
        update_cache: True
    - name: Install neovim
      apt:
        name:
          - neovim
    - name: Install nvim plugins
      shell: \nvim --headless -c 'autocmd User quitall' -c 'quitall'
      tags:
        - nvim
