#!/bin/bash

set -e

function main() {
    parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
    if [[ $# -eq 0 ]]; then
        ansible-playbook "$parent_path"/playbook.yml
    else
        ansible-playbook "$parent_path"/playbook.yml $@
    fi
}

main "$@"

# clean up
rm -rf "$parent_path"/entrypoint
touch "$parent_path"/entrypoint
cat > "$parent_path"/entrypoint << EOM
#!/bin/bash

if type -p /bin/zsh &> /dev/null; then
    /bin/zsh -li
elif type -p /bin/bash &> /dev/null; then
    /bin/bash -li
fi
EOM

if type -p /bin/zsh &> /dev/null; then
    /bin/zsh -li
elif type -p /bin/bash &> /dev/null; then
    /bin/bash -li
fi
