- hosts: localhost
  vars:
    source_key: "./ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - name: Update apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - core
        - dotfiles
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/core.yml
    - include: tasks/brew.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/conda.yml
    - include: tasks/cargo.yml
    - include: tasks/nvim.yml
    - include: tasks/lvim.yml
    - include: tasks/zsh.yml
